version: '2'

services:
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        ports:
            - 5671:5671
            - 5672:5672
            - 4369:4369
            - 25672:25672
            - 15671:15671
            - 15672:15672
        environment:
            RABBITMQ_DEFAULT_USER: admin
            RABBITMQ_DEFAULT_PASS: 123qwe